export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST'
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS'
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL'

export const RESTAURANT_DELETE_REQUEST = 'RESTAURANT_DELETE_REQUEST'
export const RESTAURANT_DELETE_SUCCESS = 'RESTAURANT_DELETE_SUCCESS'
export const RESTAURANT_DELETE_FAIL = 'RESTAURANT_DELETE_FAIL'

export const RESTAURANT_CREATE_REQUEST = 'RESTAURANT_CREATE_REQUEST'
export const RESTAURANT_CREATE_SUCCESS = 'RESTAURANT_CREATE_SUCCESS'
export const RESTAURANT_CREATE_FAIL = 'RESTAURANT_CREATE_FAIL'
export const RESTAURANT_CREATE_RESET = 'RESTAURANT_CREATE_RESET'

export const RESTAURANT_UPDATE_REQUEST = 'RESTAURANT_UPDATE_REQUEST'
export const RESTAURANT_UPDATE_SUCCESS = 'RESTAURANT_UPDATE_SUCCESS'
export const RESTAURANT_UPDATE_FAIL = 'RESTAURANT_UPDATE_FAIL'
export const RESTAURANT_UPDATE_RESET = 'RESTAURANT_UPDATE_RESET'

export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST'
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS'
export const RESTAURANT_DETAILS_FAIL = 'RESTAURANT_DETAILS_FAIL'
export const RESTAURANT_DETAILS_RESET = 'RESTAURANT_DETAILS_RESET'

export const RESTAURANT_RECENT_REVIEWED_REQUEST = 'RESTAURANT_RECENT_REVIEWED_REQUEST'
export const RESTAURANT_RECENT_REVIEWED_SUCCESS = 'RESTAURANT_RECENT_REVIEWED_SUCCESS'
export const RESTAURANT_RECENT_REVIEWED_FAIL = 'RESTAURANT_RECENT_REVIEWED_FAIL'
export const RESTAURANT_RECENT_REVIEWED_RESET = 'RESTAURANT_RECENT_REVIEWED_RESET'

export const RESTAURANT_CREATE_REVIEW_REQUEST = 'RESTAURANT_CREATE_REVIEW_REQUEST'
export const RESTAURANT_CREATE_REVIEW_SUCCESS = 'RESTAURANT_CREATE_REVIEW_SUCCESS'
export const RESTAURANT_CREATE_REVIEW_FAIL = 'RESTAURANT_CREATE_REVIEW_FAIL'
export const RESTAURANT_CREATE_REVIEW_RESET = 'RESTAURANT_CREATE_REVIEW_RESET'

export const YELP_RESTAURANT_SAVE_REQUEST = 'YELP_RESTAURANT_SAVE_REQUEST'
export const YELP_RESTAURANT_SAVE_SUCCESS = 'YELP_RESTAURANT_SAVE_SUCCESS'
export const YELP_RESTAURANT_SAVE_FAIL = 'YELP_RESTAURANT_SAVE_FAIL'
export const YELP_RESTAURANT_SAVE_RESET = 'YELP_RESTAURANT_SAVE_RESET'

export const RESTAURANT_TOP_RATED_REQUEST = 'RESTAURANT_TOP_RATED_REQUEST'
export const RESTAURANT_TOP_RATED_SUCCESS = 'RESTAURANT_TOP_RATED_SUCCESS'
export const RESTAURANT_TOP_RATED_FAIL = 'RESTAURANT_TOP_RATED_FAIL'

export const RESTAURANT_DELETE_REVIEW_REQUEST = 'RESTAURANT_DELETE_REVIEW_REQUEST'
export const RESTAURANT_DELETE_REVIEW_SUCCESS = 'RESTAURANT_DELETE_REVIEW_SUCCESS'
export const RESTAURANT_DELETE_REVIEW_FAIL = 'RESTAURANT_DELETE_REVIEW_FAIL'
