export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_LOGIN_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const OTHER_USER_DETAILS_REQUEST = 'OTHER_USER_DETAILS_REQUEST'
export const OTHER_USER_DETAILS_SUCCESS = 'OTHER_USER_DETAILS_SUCCESS'
export const OTHER_USER_DETAILS_FAIL = 'OTHER_USER_DETAILS_FAIL'
export const OTHER_USER_DETAILS_RESET = 'OTHER_USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const USER_LIKE_RESTAURANT_REQUEST = 'USER_LIKE_RESTAURANT_REQUEST'
export const USER_LIKE_RESTAURANT_SUCCESS = 'USER_LIKE_RESTAURANT_SUCCESS'
export const USER_LIKE_RESTAURANT_FAIL = 'USER_LIKE_RESTAURANT_FAIL'

export const USER_UNLIKE_RESTAURANT_REQUEST = 'USER_UNLIKE_RESTAURANT_REQUEST'
export const USER_UNLIKE_RESTAURANT_SUCCESS = 'USER_UNLIKE_RESTAURANT_SUCCESS'
export const USER_UNLIKE_RESTAURANT_FAIL = 'USER_UNLIKE_RESTAURANT_FAIL'